export const portfolioData = {
    name: "Jignesh Kalambe",
    role: "Full Stack Developer",
    location: "Surat, Gujarat",
    experience: "1.5+ years",
    currentCompany: "Include Technology",
    intro: "Full Stack Developer with 1.5+ years of production experience building scalable platforms with Next.js, React, Node.js, PWA, and AI-assisted development.",
    about: "I'm a Full Stack Developer at Include Technology, where I've shipped 4+ production platforms — including a gaming platform serving 1,000+ daily users, a precision geolocation addressing system, and a spiritual audio streaming app. I specialize in performance engineering (Lighthouse 90→100 on desktop), multi-language localization (12 languages via LibreTranslate), PWA development with push notifications, and SEO architecture. I actively leverage AI tools like Claude MCP for rapid prototyping, bootstrapping, and game logic development.",
    skills: [
        {
            category: "Frontend",
            items: ["Next.js", "React.js", "JavaScript (ES6+)", "HTML5", "CSS3", "Tailwind CSS", "shadcn/ui", "Material UI", "GSAP"],
        },
        {
            category: "Backend",
            items: ["Node.js", "Express.js", "REST APIs"],
        },
        {
            category: "Database",
            items: ["MongoDB"],
        },
        {
            category: "Performance & SEO",
            items: ["Lighthouse", "Core Web Vitals", "Lazy Loading", "Code Splitting", "Metadata", "Sitemap", "OG Tags"],
        },
        {
            category: "DevOps & CI/CD",
            items: ["Git", "GitHub", "Vercel", "GitHub Actions", "Docker"],
        },
        {
            category: "Specialized",
            items: ["PWA Development", "Push Notifications", "Multi-Language Localization", "Google AdSense", "Offline Support"],
        },
        {
            category: "AI & Productivity",
            items: ["Prompt Engineering", "AI-Assisted Development", "Claude MCP", "ElevenLabs API", "HeyGen API"],
        },
        {
            category: "Tools",
            items: ["VS Code", "Postman", "GTM", "Google AdSense", "Godot Engine"],
        },
    ],
    projects: [
        {
            title: "Online Game Platform",
            link: "https://onlinegameweb.com",
            github: "",
            description: "Solo-built a browser gaming platform with 15+ game categories serving 1,000+ daily users. Features a 12-language localization engine (LibreTranslate), PWA with push notifications & offline support, Google AdSense integration, and 2 custom Godot Engine games (3D 2048, Level Devil–style platformer) exported to WebGL. Achieved Lighthouse scores of 90→100 desktop / 65→80 mobile.",
            tech: ["Next.js", "React.js", "Tailwind CSS", "PWA", "LibreTranslate API", "Google AdSense", "Godot Engine"],
            image: "/images/onlinegameweb.webp",
            highlights: ["1,000+ daily users", "12 languages", "Lighthouse 100"],
        },
        {
            title: "My Digital PIN",
            link: "https://mydigitalpin.com",
            github: "",
            description: "Solo-built a full-stack geolocation addressing platform inspired by India Post DigiPin, with 4×4m precision accuracy. Features an interactive map, real-time geolocation, DIGIPIN generation, QR codes, WhatsApp/SMS/Email sharing, business listings, favorites, and location history. Offline-first via open-source grid logic.",
            tech: ["Next.js", "React.js", "Node.js", "Tailwind CSS", "REST APIs", "Geolocation API", "QR Generation"],
            image: "/images/mydigitalpin.webp",
            highlights: ["4×4m accuracy", "Offline-first", "QR sharing"],
        },
        {
            title: "Bhakt Chintamani",
            link: "https://bhaktchintamani.com",
            github: "",
            description: "Gujarati spiritual audio streaming platform with a custom audio player featuring progress tracking, bookmarks, and chapter navigation. Built with full SEO architecture (structured metadata, OG tags, Twitter cards) and GTM + analytics configuration.",
            tech: ["Next.js", "React.js", "Tailwind CSS", "Custom Audio Player", "SEO", "GTM"],
            image: "/images/bhaktchintamani.webp",
            highlights: ["Custom audio player", "SEO optimized", "GTM analytics"],
        },
        {
            title: "Innvolution",
            link: "https://innvolution.com",
            github: "",
            description: "Contributed 6–8 months to Asia's leading Cath Lab manufacturer's corporate website. Delivered new pages, UI/UX improvements, performance optimization, and usability enhancements for a large-scale production site.",
            tech: ["React.js", "Tailwind CSS", "GSAP"],
            image: "/images/innvolution.webp",
            highlights: ["6–8 months", "Production scale", "GSAP animations"],
        },
        {
            title: "Medical Content Automation",
            link: "https://github.com/jigneshkalambe/Medical-Content-Automation",
            github: "https://github.com/jigneshkalambe/Medical-Content-Automation",
            description: "Personal automation pipeline that converts patient scripts (+ optional images) into AI voiceover audio or AI avatar videos. Integrates ElevenLabs for text-to-speech and HeyGen for AI video generation, supporting both audio-only and full video output modes.",
            tech: ["Next.js", "Node.js", "ElevenLabs API", "HeyGen API", "REST APIs"],
            image: "/images/medical-automation.webp",
            highlights: ["AI voiceover", "AI avatar video", "Automation pipeline"],
        },
    ],
    workExperience: [
        {
            company: "Include Technology",
            role: "Full Stack Developer",
            period: "Aug 2024 – Present",
            type: "Onsite · Surat",
            responsibilities: [
                "Built and deployed 4+ production platforms across gaming, geolocation, and content domains",
                "Built a 12-language localization engine using LibreTranslate API with a custom auto-analyze/translate/JSON-generation script",
                "Integrated Google AdSense from scratch; implemented PWA features including push notifications and offline support",
                "Improved Lighthouse scores from 90→100 (desktop) and 65→80 (mobile) through performance engineering",
                "Built UI systems using Tailwind CSS + shadcn/ui; integrated REST APIs across multiple projects",
                "Contributed 6–8 months to Innvolution, Asia's leading Cath Lab manufacturer's corporate site",
                "Used Claude MCP and AI tools for bootstrapping, prototyping, and game logic development",
            ],
        },
        {
            company: "Include Technology",
            role: "Full Stack Developer Intern",
            period: "July 2024 · 1 month",
            type: "Onsite · Surat",
            responsibilities: [
                "Assisted on production applications built with Next.js and React.js",
                "Gained hands-on experience with REST API integration and dynamic UI development",
                "Contributed to frontend performance optimization tasks",
            ],
        },
    ],
    education: [
        {
            degree: "Full Stack Development",
            institution: "Simba Institute",
            location: "Surat",
            period: "2023 – 2024",
            credential: "Certified Full Stack Developer",
        },
        {
            degree: "HSC",
            institution: "Akhand Anand Vidhya Bhavan",
            location: "Surat",
            period: "2022 – 2023",
            credential: "74%",
        },
    ],
    contact: {
        email: "jigneshkalambe63@gmail.com",
        phone: "+91-9586040515",
        linkedin: "https://www.linkedin.com/in/jignesh-kalambe",
        github: "https://github.com/jigneshkalambe",
        location: "Surat, Gujarat",
        resume: "/resume.pdf",
    },
};
